// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tprofomqlsurdxvcavlj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwcm9mb21xbHN1cmR4dmNhdmxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4ODc1MDEsImV4cCI6MjA1MjQ2MzUwMX0.0ISTVA-pOb94oMoKMgg59h3KIL_86lTvjoInFtRrfTk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);